spring.application.name=ticket-api
server.port=8081

app.notification.base-url=http://localhost:8082

spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:sqlite:ticket-db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
