spring.application.name=user-api
server.port=8080

app.user.default.roles=ROLE_USER,ROLE_GUEST,ROLE_VIEWER
app.ticket.base-url=http://localhost:8081

spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:sqlite:user-db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

app.pagination.max-size=1000

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
